// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function answer() {
  const fibonacci = [1, 2];
  const evens = [2];

  while (fibonacci[fibonacci.length - 1] <= 4000000) {
    const last = fibonacci[fibonacci.length - 1];
    const nextToLast = fibonacci[fibonacci.length - 2];

    const next = nextToLast + last;

    if (next % 2 === 0) {
      evens.push(next);
    }

    fibonacci.push(next);
  }

  return evens.reduce((a, b) => a + b, 0);
}

const logAnswer = require('../utils/logAnswer');
logAnswer(answer);
